name: infra deploy

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: "23d4f819-c0d7-4465-a64e-666f81bdf2ef"
  ARM_CLIENT_SECRET: ${{secrets.AZ_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: "fefb2c8c-7f96-4a73-816f-9b0722d2d305"
  ARM_TENANT_ID: "1abdabec-ba82-4839-98be-47802e8fad31"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout git repo
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        name: setup terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - if: github.ref == 'refs/heads/master'
        name: Terraform Apply
        run: terraform apply -auto-approve
